import type {
  AssistantModuleDefinition,
  AssistantModuleKey,
} from "@/features/assistant/types"

export const presetModuleLibrary: Record<
  AssistantModuleKey,
  AssistantModuleDefinition
> = {
  "title-region": {
    moduleKey: "title-region",
    moduleName: "标题区",
    modulePurpose: "定义页面身份、时间范围、组织对象和当前方案标题。",
    commonTitles: ["驾驶舱总览", "运行总览", "能碳总览", "页面说明"],
    commonDataItems: ["页面标题", "组织名称", "时间范围", "方案摘要"],
    commonChartTypes: ["文字区块", "状态标签"],
    commonRegions: ["顶部标题区"],
    suitableQuestions: ["这是什么页面？", "当前方案面向谁？"],
  },
  "filter-region": {
    moduleKey: "filter-region",
    moduleName: "筛选区",
    modulePurpose: "收敛当前查看范围，明确组织、时间和对象维度。",
    commonTitles: ["筛选条件", "查看范围", "当前维度"],
    commonDataItems: ["年份", "工厂", "园区", "业务单元"],
    commonChartTypes: ["筛选控件", "标签"],
    commonRegions: ["顶部标题区", "页头右侧"],
    suitableQuestions: ["当前看的是哪一层数据？", "筛选口径是什么？"],
  },
  "kpi-overview": {
    moduleKey: "kpi-overview",
    moduleName: "KPI 总览卡",
    modulePurpose: "快速展示当前页面最重要的核心指标和对比结果。",
    commonTitles: ["核心指标", "本期总览", "关键 KPI"],
    commonDataItems: ["总量", "同比", "环比", "完成率"],
    commonChartTypes: ["指标卡"],
    commonRegions: ["中间总览区", "顶部下方"],
    suitableQuestions: ["当前整体表现如何？", "本期结果是否达标？"],
  },
  "trend-analysis": {
    moduleKey: "trend-analysis",
    moduleName: "趋势分析模块",
    modulePurpose: "解释时间维度上的变化，帮助判断走势和波动。",
    commonTitles: ["月度趋势", "趋势变化", "阶段走势"],
    commonDataItems: ["近 12 个月趋势", "同比变化", "波动区间"],
    commonChartTypes: ["折线图", "面积折线图"],
    commonRegions: ["左侧分析区", "中部下方"],
    suitableQuestions: ["最近是在上升还是下降？", "波动最明显的阶段在哪？"],
  },
  "composition-breakdown": {
    moduleKey: "composition-breakdown",
    moduleName: "结构占比模块",
    modulePurpose: "解释构成关系，帮助判断各部分占比和来源。",
    commonTitles: ["结构占比", "构成分析", "来源构成"],
    commonDataItems: ["分类占比", "来源构成", "类型分布"],
    commonChartTypes: ["环图", "堆叠柱图"],
    commonRegions: ["左侧分析区", "右侧分析区"],
    suitableQuestions: ["主要由哪些部分构成？", "哪一类占比最高？"],
  },
  "ranking-module": {
    moduleKey: "ranking-module",
    moduleName: "排名模块",
    modulePurpose: "比较管理对象之间的差异，帮助快速识别高低位对象。",
    commonTitles: ["对象排行", "工厂排行", "项目排行"],
    commonDataItems: ["排行值", "对象名称", "差值对比"],
    commonChartTypes: ["横向条形图"],
    commonRegions: ["右侧排行区", "中部辅助区"],
    suitableQuestions: ["谁最高？", "差异主要来自哪些对象？"],
  },
  "target-progress": {
    moduleKey: "target-progress",
    moduleName: "目标达成模块",
    modulePurpose: "表达目标值、完成率和差距，帮助判断当前管理压力。",
    commonTitles: ["目标达成", "目标对比", "达成进度"],
    commonDataItems: ["目标值", "当前值", "完成率", "差距"],
    commonChartTypes: ["进度条", "环形进度"],
    commonRegions: ["右侧目标区", "中部辅助区"],
    suitableQuestions: ["距离目标还有多远？", "当前是否达标？"],
  },
  "alert-module": {
    moduleKey: "alert-module",
    moduleName: "预警模块",
    modulePurpose: "突出异常项、风险项和待处理事项。",
    commonTitles: ["预警列表", "风险提醒", "异常概览"],
    commonDataItems: ["预警级别", "异常对象", "触发时间", "处理状态"],
    commonChartTypes: ["列表", "状态卡"],
    commonRegions: ["右侧预警区", "中部告警区"],
    suitableQuestions: ["当前最需要处理什么？", "异常主要集中在哪？"],
  },
  "detail-table": {
    moduleKey: "detail-table",
    moduleName: "表格 / 明细模块",
    modulePurpose: "补充对象级明细和追溯信息，支持继续核对和交付说明。",
    commonTitles: ["明细列表", "工厂明细", "异常明细"],
    commonDataItems: ["对象名称", "明细值", "状态", "更新时间"],
    commonChartTypes: ["表格"],
    commonRegions: ["底部明细区"],
    suitableQuestions: ["具体明细是什么？", "后续如何继续核对？"],
  },
  "narrative-note": {
    moduleKey: "narrative-note",
    moduleName: "说明文案模块",
    modulePurpose: "把页面逻辑、默认假设和执行建议整理成可继续传达的说明文本。",
    commonTitles: ["页面说明", "执行说明", "默认假设"],
    commonDataItems: ["方案摘要", "执行说明", "假设条件"],
    commonChartTypes: ["文本区块"],
    commonRegions: ["底部说明区", "页面尾部"],
    suitableQuestions: ["为什么这样组织页面？", "下一步应该怎么继续？"],
  },
}

export const presetModuleList = Object.values(presetModuleLibrary)
