/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BaoxiniaoRouteImport } from './routes/baoxiniao'
import { Route as IndexRouteImport } from './routes/index'

const BaoxiniaoRoute = BaoxiniaoRouteImport.update({
  id: '/baoxiniao',
  path: '/baoxiniao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baoxiniao': typeof BaoxiniaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baoxiniao': typeof BaoxiniaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baoxiniao': typeof BaoxiniaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baoxiniao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baoxiniao'
  id: '__root__' | '/' | '/baoxiniao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaoxiniaoRoute: typeof BaoxiniaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/baoxiniao': {
      id: '/baoxiniao'
      path: '/baoxiniao'
      fullPath: '/baoxiniao'
      preLoaderRoute: typeof BaoxiniaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaoxiniaoRoute: BaoxiniaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
